#! /bin/bash

set -uxe

kubectl create secret -n kube-system generic kube-dashboard-secrets --from-literal=client_id=$CLIENT_ID --from-literal=client_secret=$CLIENT_SECRET --from-literal=session=12345asd
