#! /bin/bash

set -exu

kubectl config set-context --user minikube --cluster minikube --namespace kube-system mk-system
kubectl config use-context mk-system

kubectl apply -f roles.yaml --validate=false
