#! /bin/bash

set -exu

code=$1

curl -X POST \
  --data-urlencode "grant_type=authorization_code" \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$CLIENT_SECRET" \
  --data-urlencode "redirect_uri=http://localhost:3000/oauth2/callback" \
  --data-urlencode "code=$code" \
  https://pvdvreede.au.auth0.com/oauth/token | jq .
